sudo: required
language: go

dist: bionic

go:
- "1.13"

script:
- docker buildx version
- make docker || travis_terminate 1;
- make dist

before_script:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update -qy
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo systemctl start docker
  - ./hack/install-buildx.sh

after_success:
  - make docker-login
  - make docker-login-ghcr
  - make push
  - make push-ghcr

before_deploy:
  - ./ci/hashgen.sh

deploy:
  provider: releases
  api_key:
    secure: R181wN4fkK0LcJylzNCSZg5EeEZnLdh4YwvEBrRtTAaZ54uTApz2QB+jmrPBNgxM2/7j/f603ZHvibb6qgkKjSAhnq7O8nOdgyMyoDFrMmnq8deWmg1oFo+MPpiQ/2GaYJ2gVEukXLVSuFriL+Om4JmJbzWEJXsDToK/ffr6BlkV5589NetHyuGPHKqgneAbkpTIFOHCbE+6hBUHxFNxyMUpyYpTEENMp0k2ZIW3kN88IVyE00JzbCzac4/U0DXGJJZF/wGCFh1jRdKP5YcLpFOcNmFqtrGK77XjAorPzmk5djbl5Q8FeZJVPC9Foi6iIQZ5K+dHGJXiK86RH4QCRv4uJ1PtGfqRY6ygM92PU7zaCwhPPJydbXKGovLgPL1ht2DiTAhabT4ujjUNH5H/eAUW1D4ZJiKXgTrMpY/Cqq7egXJIvViAswv4rLOUbKyn0XxH7phYUaIeOzgue0Hzmg7w6+DDdeO86BduZ+Jz1wUlJougZLO/L2B4fuOVCH8rUXH3jXf27vwG8x9k5x1WOLKJSO8LzQTIJ69NgW3uCYIMvKe+gc6qdWf+kTVtI3nWV6+yo4q4s++I9iqhXuWECcR/0B9viMltGwnRoNB5Y43Fff/v7wI/iWHqIT12WwE3QCw6yqbQ+B5KyMiYjHYyQhv+eymii2+51nV6x2UwHp4=
  file:
    - ./bin/inlets
    - ./bin/inlets-darwin
    - ./bin/inlets-freebsd
    - ./bin/inlets-armhf
    - ./bin/inlets-arm64
    - ./bin/inlets.exe
    - ./bin/inlets.sha256
    - ./bin/inlets-darwin.sha256
    - ./bin/inlets-freebsd.sha256
    - ./bin/inlets-armhf.sha256
    - ./bin/inlets-arm64.sha256
    - ./bin/inlets.exe.sha256
  skip_cleanup: true
  on:
    tags: true

env: GO111MODULE=off

